"use client";

import { useState } from "react";

interface TerminalOutputProps {
  output: string;
  isLoading: boolean;
  error: Error | undefined;
  rawContext?: string;
}

export function TerminalOutput({ output, isLoading, error, rawContext }: TerminalOutputProps) {
  const isEmpty = !output && !isLoading && !error;
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    if (!output) return;
    const hasContext = Boolean(rawContext?.trim());

    // Append prospect context if the user pasted notes — staples their intel
    // onto the end of the master prompt so the downstream AI has full context.
    // The [THE INTERACTIVE KICKOFF] section is already generated by the engine
    // as section 6 — do not append anything after it.
    const intel = hasContext
      ? `\n\n---\n\n## PROSPECT CONTEXT\n\n${rawContext!.trim()}`
      : "";

    navigator.clipboard.writeText(output + intel).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  /* ── Empty skeleton ── */
  if (isEmpty) {
    return (
      <div className="w-full min-h-[120px] bg-zinc-900/50 border border-zinc-800 rounded-lg flex items-center justify-center">
        <p className="font-mono text-sm text-zinc-600 select-none">
          Generated prompt will appear here...
        </p>
      </div>
    );
  }

  /* ── Active state (loading / output / error) ── */
  return (
    <div className="w-full border border-white/10 bg-black/40 backdrop-blur-md rounded-lg overflow-hidden">
      {/* Header bar */}
      <div className="flex items-center gap-2 px-4 py-2.5 border-b border-white/10 bg-white/[0.02]">
        <span
          className="h-1.5 w-1.5 rounded-full bg-primary"
          style={{ boxShadow: "0 0 6px rgba(255,51,0,0.9)" }}
        />
        <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground/50">
          Generated Prompt
        </span>

        <div className="ml-auto flex items-center gap-3">
          {isLoading && (
            <span className="font-mono text-[10px] text-primary animate-pulse">
              Generating...
            </span>
          )}
          {output && !isLoading && (
            <button
              onClick={handleCopy}
              className="font-mono text-[10px] uppercase tracking-widest transition-colors duration-150 px-2 py-1 rounded-sm border border-white/10 hover:border-primary/40 hover:bg-primary/5"
              style={copied ? { color: "rgb(255,51,0)", borderColor: "rgba(255,51,0,0.4)" } : { color: "rgba(113,113,122,0.7)" }}
            >
              {copied ? "Copied ✓" : rawContext?.trim() ? "Copy + Context" : "Copy"}
            </button>
          )}
        </div>
      </div>

      {/* Body — auto-expands with content */}
      <div
        className="px-5 py-5 max-h-[520px] overflow-y-auto"
        style={{
          scrollbarWidth: "thin",
          scrollbarColor: "rgba(255,51,0,0.15) transparent",
        }}
      >
        {error && (
          <p className="font-mono text-xs text-red-400/80">
            Error: {error.message}
          </p>
        )}

        {output && (
          <pre className="font-mono text-sm text-foreground/90 whitespace-pre-wrap leading-relaxed">
            {output}
            {isLoading && (
              <span
                className="inline-block w-[7px] h-[14px] bg-primary ml-0.5 align-middle animate-pulse"
                style={{ boxShadow: "0 0 8px rgba(255,51,0,0.8)" }}
              />
            )}
          </pre>
        )}

        {isLoading && !output && (
          <span
            className="inline-block w-[7px] h-[14px] bg-primary animate-pulse"
            style={{ boxShadow: "0 0 8px rgba(255,51,0,0.8)" }}
          />
        )}
      </div>
    </div>
  );
}
